### PR TITLE
WIP Package for app distribution

### PR DESCRIPTION
**Pull request by finned-palmer**
Rearranges the repo around app distribution, adds necessary files for app distribution packaging.

Do not merge yet, need to get it to actually run.

cc @taalhavras @willbach @jalehman 

Todo list:

- [x] Add package-related meta files.
- [x] Move everything to where it's supposed to go.
- [x] Copy necessary libs from landscape.
- [ ] Get frontend up and running (incoming commit, I have some changes from a different branch I was working on).
- [ ] Update scries
- [ ] Figure out what's going on with the ucal-push-hook not compiling in some cases.

### CODE REVIEW

**Comment by taalhavras** [comment]
Just posting an update - I've been messing with this and still haven't gotten to the bottom of the push-hook issue. Doesn't seem to be much info on this anywhere which means either 1) It's something weird and nasty or 2) it's something especially dumb. Stack trace for reference https://www.toptal.com/developers/hastebin/ikukehiyam.js

**Comment by taalhavras** [comment]
with the last two changes all the apps build and run fine. I'm still having an issue navigating to the calendar page (currently http://localhost:8082/apps/calendar just shows a black screen).

**Comment by finned-palmer** [comment]
Awesome. I can take a look at the webpack config.

**Comment by taalhavras** [comment]
Alright after the latest changes I made everything here works. There are still things to improve on the UI (might make separate issues for those) but after this there's nothing stopping us from packaging this up for distribution. I will set up a host moon sometime this week.

**Comment by finned-palmer** [comment]
Nice work @taalhavras!

**Pull request merged**
